using System.Collections;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class FoodItemModel
{
    [RealtimeProperty(1, true, true)]
    private string _creator;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class FoodItemModel : RealtimeModel {
    public string creator {
        get {
            return _creatorProperty.value;
        }
        set {
            if (_creatorProperty.value == value) return;
            _creatorProperty.value = value;
            InvalidateReliableLength();
            FireCreatorDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(FoodItemModel model, T value);
    public event PropertyChangedHandler<string> creatorDidChange;
    
    public enum PropertyID : uint {
        Creator = 1,
    }
    
    #region Properties
    
    private ReliableProperty<string> _creatorProperty;
    
    #endregion
    
    public FoodItemModel() : base(null) {
        _creatorProperty = new ReliableProperty<string>(1, _creator);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _creatorProperty.UnsubscribeCallback();
    }
    
    private void FireCreatorDidChange(string value) {
        try {
            creatorDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _creatorProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _creatorProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.Creator: {
                    changed = _creatorProperty.Read(stream, context);
                    if (changed) FireCreatorDidChange(creator);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _creator = creator;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
