using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class UserModel
{
    [RealtimeProperty(1, true, true)]
    private string _username;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class UserModel : RealtimeModel {
    public string username {
        get {
            return _usernameProperty.value;
        }
        set {
            if (_usernameProperty.value == value) return;
            _usernameProperty.value = value;
            InvalidateReliableLength();
            FireUsernameDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(UserModel model, T value);
    public event PropertyChangedHandler<string> usernameDidChange;
    
    public enum PropertyID : uint {
        Username = 1,
    }
    
    #region Properties
    
    private ReliableProperty<string> _usernameProperty;
    
    #endregion
    
    public UserModel() : base(null) {
        _usernameProperty = new ReliableProperty<string>(1, _username);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _usernameProperty.UnsubscribeCallback();
    }
    
    private void FireUsernameDidChange(string value) {
        try {
            usernameDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _usernameProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _usernameProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.Username: {
                    changed = _usernameProperty.Read(stream, context);
                    if (changed) FireUsernameDidChange(username);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _username = username;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
