using System.Collections;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class RoamingAgentFoodModel
{
    [RealtimeProperty(1, true, false)]
    private int _count;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class RoamingAgentFoodModel : RealtimeModel {
    public int count {
        get {
            return _countProperty.value;
        }
        set {
            if (_countProperty.value == value) return;
            _countProperty.value = value;
            InvalidateReliableLength();
        }
    }
    
    public enum PropertyID : uint {
        Count = 1,
    }
    
    #region Properties
    
    private ReliableProperty<int> _countProperty;
    
    #endregion
    
    public RoamingAgentFoodModel() : base(null) {
        _countProperty = new ReliableProperty<int>(1, _count);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _countProperty.UnsubscribeCallback();
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _countProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _countProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.Count: {
                    changed = _countProperty.Read(stream, context);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _count = count;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
