using Normal.Realtime.Serialization;
using System.Collections.Generic;
using Normal.Realtime;

[RealtimeModel]
public partial class RoamingAgentModel
{
    [RealtimeProperty(1, true, true)]
    private RealtimeDictionary<RoamingAgentFoodModel> _tamingStatus;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class RoamingAgentModel : RealtimeModel {
    public Normal.Realtime.Serialization.RealtimeDictionary<RoamingAgentFoodModel> tamingStatus {
        get => _tamingStatus;
    }
    
    public enum PropertyID : uint {
        TamingStatus = 1,
    }
    
    #region Properties
    
    private ModelProperty<Normal.Realtime.Serialization.RealtimeDictionary<RoamingAgentFoodModel>> _tamingStatusProperty;
    
    #endregion
    
    public RoamingAgentModel() : base(null) {
        RealtimeModel[] childModels = new RealtimeModel[1];
        
        _tamingStatus = new Normal.Realtime.Serialization.RealtimeDictionary<RoamingAgentFoodModel>();
        childModels[0] = _tamingStatus;
        
        SetChildren(childModels);
        
        _tamingStatusProperty = new ModelProperty<Normal.Realtime.Serialization.RealtimeDictionary<RoamingAgentFoodModel>>(1, _tamingStatus);
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _tamingStatusProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _tamingStatusProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.TamingStatus: {
                    changed = _tamingStatusProperty.Read(stream, context);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _tamingStatus = tamingStatus;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
